title: Res Top Down
permalink: /:title.html
baseurl: "restopdown.github.io"
site_url: "restopdown.github.io"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME

timezone: Asia/Ho_Chi_Minh
date_format: "%d-%m-%Y"
