title: Res Top Down
permalink: /:title.html
name : Resource Top Download
baseurl: ""
site_url: ""

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME

timezone: Asia/Ho_Chi_Minh
date_format: "%d-%m-%Y"
